export const REQUEST_POSTS_PENDING = "REQUEST_POSTS_PENDING";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED";
export const SET_SEARCHED_USER = "SET_SEARCHED_USER";

export const REQUEST_USERS_PENDING = "REQUEST_USERS_PENDING";
export const REQUEST_USERS_SUCCESS = "REQUEST_USERS_SUCCESS";
export const REQUEST_USERS_FAILED = "REQUEST_USERS_FAILED";

export const SET_USER_ID = "SET_USER_ID";
